repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: forbid-yaml-extension
        name: Forbid .yaml files (use .yml instead)
        entry: '.yaml files are not allowed. Please use .yml extension instead.'
        language: fail
        files: 'datasets/.*\.yaml$'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ['--select', 'I', '--fix']
      - id: ruff-format
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.1
    hooks:
      - id: mypy
        # Don't run isolated but use the activated venv. Not perfect but better than re-declaring all deps here
        language: system
        exclude: |
          (?x)^(
          zavod/zavod/tests|
          contrib/|
          .pywikibot/|
          datasets/_analysis|
          datasets/_collections|
          datasets/_externals|
          datasets/_global|
          datasets/_testing|
          datasets/_wikidata|
          datasets/ae|
          datasets/am|
          datasets/ar|
          datasets/at|
          datasets/au|
          datasets/az|
          datasets/ba|
          datasets/be|
          datasets/bg|
          datasets/bh|
          datasets/br|
          datasets/ca|
          datasets/ch|
          datasets/cl|
          datasets/cn|
          datasets/co|
          datasets/cu|
          datasets/cy|
          datasets/cz|
          datasets/de|
          datasets/dk|
          datasets/ee|
          datasets/eg|
          datasets/es|
          datasets/eu|
          datasets/fr|
          datasets/gb|
          datasets/ge|
          datasets/gg|
          datasets/hk|
          datasets/hr|
          datasets/id|
          datasets/ie|
          datasets/il|
          datasets/im|
          datasets/in|
          datasets/iq|
          datasets/ir|
          datasets/is|
          datasets/jp|
          datasets/kg|
          datasets/kp|
          datasets/ky|
          datasets/kz|
          datasets/li|
          datasets/lt|
          datasets/lu|
          datasets/lv|
          datasets/mc|
          datasets/md|
          datasets/me|
          datasets/mk|
          datasets/mt|
          datasets/mx|
          datasets/my|
          datasets/ng|
          datasets/nl|
          datasets/no|
          datasets/np|
          datasets/nz|
          datasets/ph|
          datasets/pk|
          datasets/pl|
          datasets/ps|
          datasets/qa|
          datasets/ro|
          datasets/rs|
          datasets/ru|
          datasets/sg|
          datasets/si|
          datasets/sk|
          datasets/th|
          datasets/tj|
          datasets/tr|
          datasets/tw|
          datasets/ua|
          datasets/us|
          datasets/uy|
          datasets/ve|
          datasets/xk|
          datasets/za
          )
        args: ['--strict']
  - repo: local
    hooks:
      - id: nextjs-lint
        name: Next.js ESLint
        entry: bash -c "cd ui && npx next lint --fix"
        language: system
        files: '^ui/'
        pass_filenames_to_command: false
