services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      # Changed from 5432 to 5444 to avoid port conflicts
      - "5444:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  os-db: null
